{% set name = "pytest-flakes" %}
{% set version = "4.0.3" %}
{% set sha256 = "bf070c5485dad82d5b5f5d0eb08d269737e378492d9a68f5223b0a90924c7754" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - pytest-cache
    - pytest >=2.4.0
    - pyflakes

test:
  imports:
    - pytest_flakes


about:
  home: https://github.com/fschulze/pytest-flakes
  license: MIT
  license_file: LICENSE
  summary: pytest plugin to check source code with pyflakes

extra:
  recipe-maintainers:
    - bjodah
    - asmeurer
