travis:
  secure:
    BINSTAR_TOKEN: W7mYYS48vWncwzAcuXgykCEZ4/x6OP7mD2qUWOujOovQIT9fyQn1n6an0xCUd1bSHBefX1qP3Tm12dUYUgmQMnALqh7l5DB6wAxFfgxva+2mgB6auvI6PRpaA0gQK0sDkFvI6vlCbMaLmEO0L7u1bRFTr7ljaAqo5kz781xh+/+aMHK5mof3tFgaTnwnA5i1+aLlaVhv4APmn9SHEZ3yEwRr9VBnBqUOh7gVEF+biblKMxRp1Pf3yEyQwjPa2UESR44Y9LSXfjFKIoaOAWNril3GvXhYxOkKUCHCmVG0pKreJ+9VAADqk6qDpVrJ+9muCEmxIUCKsFLgexAMiMXj5/WgJgDsGocBuMciPtjAOpufryah+xNXSx2utdITUWiONtGlcSkXkI7qmzT2EOgIsJqfzb5zWfQE0QmPmNREFEatZCBU7pbDmzDU1WWXu8QD3YhawU0jgaXgG35jkGJy++ilj80FBeVTmN7CTLoJFYJohtNFqWVQY48ZOa1zMnExhepAdv+2Ass0ys6OKAWOGbAKLAcmPgfBLPy1wVHDFyozQEC788hExTJnFUxnNnLGTANv6oxpRODG7CMV5YxVjDOEIVRw/9zjFnCH8jfEzNYNSxIn3Wo4q+szyHJ0SaC1LjtNUCJKX/VY0Z7///FBX97x06U9JSGhJLEaOyRjAEg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
