travis:
  secure:
    BINSTAR_TOKEN: GVA+bsrS+jEkL23xfRE7xDCR9IBH/S2KkmhLc5RA6qmIM/oWV8JgrxZatR3PV/O221PbYBLJs2QeThFe8q+FRt7FBAXr5o9jx1SdwjyJcDK8JOvTrtxEhSinolCAnlQH/4d+TLfaA8sI2DdwMNyWDnlA0DpXbIv1UShKM80jIG2zJyJO5mNZGjX7QZ3qArYx2fqiFzgXnlL6nmWmFsxfz3QBY6cu5Yk8hO7GuoK3qpgadPWeGETgmbuLF5gWPiTGFViyvjwFaQcGWYYyJ+H6ddvaILNDEUtpPnHMUeldgYcWfbPSPnMo2Ttmt+OC8NQEE+DBwTZ5SLowz8Hs0VOEtotlTszidYCnGZPh+g6wcVijQP2ZBbEknhrZsRJf5i4mwHUBqr2dmryAIgOE/seLbCXXbymktyLFiYOD+4G06haHgQ0wjkpyH8ePaxs7VMARW2t7qyuLeLGJI/XgPL7HaCSxC12Rj810cOWjgbmJt63bKOrWDCimhQW8LVqLDO83A1mB4udoHKvuilo1eYfEMRQ3Oa+m/kp80EFsStEu7U115bYqc6ivhI/Du+dWU2z+QOF6llRJJ7RFPiPgqnZfWLj9iLna3QR2mwUbxl8wUhQSGp1FZoz/rgzNISDaRgqZNB6ahTZ5WNE3sQAZgHP8BvXTo5JHE3yEXljrpwaHO2M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
