travis:
  secure:
    BINSTAR_TOKEN: Xntn4n+AkIqFbxnSYgQpx6nemj3hP4V89CpbBx6XTWXcpsJHITs+QVRa1VgNOj50n8XY+EA83ccwUZSfmp3+CgcDjjEZTwpvtPn9EalnD+jDW3Ag85vryOTAsagOWnrAgCw1wRyybmEK4D6WRzKVuAEYyx3OQhIDcs1Ct5tySGBabOWMemn+WcFNt2TsvbGl43gEPqizY1e+QdpDRRq7p30gaBHGsu2lIHYpvQu/wLTYxjZySnwpfXil/sLGNNVFwR8N42cCvel+qqoMRZmT9Q2J1BOrScVZW4DHhTqF8qBXRqqZ9mtQQGqcYsDyOsWvex4z2m1I8IyWe98R7Kjr5zjm+mIj+45RIXTKXhJCczkboLU9+UThK0wsPNiHtyQ5EjScEACaoF5a9z6fhWITS8NExliDEQk6n9w2cB1HvWLTHK2nrvd24gd365Kko/gG7GF/KjNaW0HLPew6DhHBNTX60p7I5Apevo1T95dbrnZ/vatQxZR210lvQcGEEgeWwRtkGENxCW5xnD7Xo/8vP66vpoc7SEEZQji5qEoAAUMHAS/H/8UFhpnAjB5nH8RoG8PTX89r23nGBWPEy/wJ85SrTIFNCqpInaWd1zVlObK+usiCevVWnkKrIf9ZqJp5m/nK6L033pn0swPV+l6IWRhj4M0LccMKx1M7vSAolRw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
